language: python
python:
  - "2.7"
  # Disabled due to test failures like:
  # TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'
  # Needs explicit conversion to bytes after string formatting.
  # Example, see https://travis-ci.org/abhinavsingh/proxy.py/jobs/490855017
  #- "3.3"
  #- "3.4"
  - "3.5"
  - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
# This is official workaround for Python 3.7 support by Travis
# See https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
os:
  - linux
  # No support for OSX Python runtime
  #- osx
  # Windows Python support is currently in early access
  #- windows
script:
  - make
