language: python
env:
  - TESTING_ON_TRAVIS=1
matrix:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
      python: 3.7
install:
  - pip install -r requirements-testing.txt
script: python3 -m pytest --cov=proxy tests/ || python -m pytest --cov=proxy tests/
