version: "2.1"

services:
  solana:
    container_name: solana
    image: cybercoredev/solana:${SOLANA_REVISION:-v1.6.9-resources}
    environment:
      - SOLANA_URL=http://solana:8899
      - RUST_LOG=solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
    hostname: solana
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8001"
      - "8001-8009/udp"
    networks:
      - net

  proxy:
    container_name: proxy
    image: cybercoredev/proxy:${REVISION}
    environment:
      - SOLANA_URL=http://solana:8899
      - EVM_LOADER=deploy
      - ETH_TOKEN_MINT=deploy
      - COLLATERAL_POOL_BASE=deploy
      - LOCAL_CLUSTER=local
    hostname: proxy
    ports:
      - 127.0.0.1:9090:9090
    expose:
      - "9090"
    networks:
      - net

networks:
  net:
