version: "2.1"

services:
  solana:
    container_name: solana
    image: cybercoredev/solana:v1.4.25-resources
    environment:
      - SOLANA_URL=http://solana:8899
      - RUST_LOG=solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
    hostname: solana
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8001"
      - "8001-8009/udp"
    networks:
      - net

  proxy:
    container_name: proxy
    image: cybercoredev/proxy:latest
    environment:
      - SOLANA_URL=http://solana:8899
    hostname: proxy
    ports:
      - 127.0.0.1:9090:9090
    networks:
      - net

networks:
  net:
