name: Proxy.py

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macOS-latest]
    strategy:
      max-parallel: 4
      matrix:
        python: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-testing.txt
      - name: Lint Checker
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 proxy.py tests.py --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 proxy.py tests.py --count --exit-zero --max-line-length=127 --statistics
      - name: Run Tests
        run: |
          pytest tests.py
